"""
EKAYAA — Layer 4 Output Guardrails
Semantic scanner that intercepts the Worker LLM's response BEFORE it reaches the UI.

Key design decisions
────────────────────
1.  Latency budget: Layer 4 runs AFTER the LLM has streamed all tokens.
    Target scan time: <30 ms (streaming still shows the user a "checking…" state).

2.  Architecture: PubMedBERT embedding model + Qdrant, SEPARATE collection
    ("ekayaa_output_violations") seeded with the <vector_db_seeds> from each
    agent's Layer 4 block in Patterns.docx.

    Embedding model choice: pritamdeka/PubMedBERT-mnli-snli-...
    PubMedBERT is domain-tuned on clinical NLI tasks — it has finer-grained
    understanding of clinical sentence semantics (diagnosis, prognosis, treatment
    authority) than a general-purpose model.

3.  Scan strategy for "Incremental Escalation" (Taxonomy #6):
    The output scanner receives the FULL response text plus the last-N turns of
    conversation context. It checks the combined window, not just the final
    response token.

4.  Agent-specific scanning: each agent has its own prohibited output categories.
    We tag each seed with its agent so we can restrict the Qdrant search.

5.  Structural checks (XML tag leakage, Composition.status) are NOT performed.
    This guardrail is strictly semantic.

Seed file: data/output_vector_seeds.json
  (generated by: python seed_patterns.py --role output --model pritamdeka/PubMedBERT-mnli-snli-scinli-scitail-mednli-stsb
                                         --output data/output_vector_seeds.json)
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
import time
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Optional

from qdrant_client import QdrantClient
from qdrant_client.http import models as qdrant_models
from sentence_transformers import SentenceTransformer

logger = logging.getLogger("ekayaa.layer4")

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

EMBEDDING_MODEL_ID     = "pritamdeka/PubMedBERT-mnli-snli-scinli-scitail-mednli-stsb"
OUTPUT_COLLECTION_NAME = "ekayaa_output_violations"
VECTOR_DIM             = 768   # PubMedBERT hidden size

# Thresholds for output scanning.
OUTPUT_BLOCK_THRESHOLD     = 0.78
OUTPUT_GREY_ZONE_LOWER     = 0.60
OUTPUT_GREY_VOTE_THRESHOLD = 3.8
K_NEAREST                  = 5

# Context window for Incremental Escalation detection (#6)
ESCALATION_CONTEXT_TURNS = 4

# Safe fallback injected in place of a blocked response
SCRUBBED_RESPONSE_TEMPLATE = (
    "I cannot provide that information. {agent_fallback}"
)

AGENT_FALLBACKS = {
    "ADITI": "Please consult the attending physician for clinical decisions regarding this patient.",
    "DIANA": "Clinical decisions and documentation must be reviewed and approved by the responsible physician.",
    "NINA":  "Please consult the attending physician or charge nurse for clinical guidance.",
    "PAMA":  "Please speak with your doctor, nurse, or pharmacist for medical advice.",
}

# ─────────────────────────────────────────────────────────────────────────────
# Data classes
# ─────────────────────────────────────────────────────────────────────────────

class Layer4Decision(str, Enum):
    PASS    = "PASS"
    BLOCK   = "BLOCK"
    SCRUB   = "SCRUB"   # partial block: response scrubbed and replaced

@dataclass
class Layer4Result:
    decision:       Layer4Decision
    stage:          str               # "semantic" | "semantic_grey_zone" | "none"
    violation_type: Optional[str] = None
    matched_label:  Optional[str] = None
    confidence:     float         = 0.0
    latency_ms:     float         = 0.0
    safe_response:  str           = ""

# ─────────────────────────────────────────────────────────────────────────────
# Pre‑processing: strip <think> blocks (they are internal reasoning, not output)
# ─────────────────────────────────────────────────────────────────────────────

def _strip_think_blocks(text: str) -> str:
    """Remove <think>...</think> blocks before scanning visible output."""
    return re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()

# ─────────────────────────────────────────────────────────────────────────────
# Semantic scanner (PubMedBERT + Qdrant)
# ─────────────────────────────────────────────────────────────────────────────

class OutputSemanticScanner:
    """
    Primary defense against paraphrased clinical output that evades
    exact-string matching.

    Uses PubMedBERT (domain-tuned on clinical NLI) — deliberately kept
    different from Layer 1's BGE-large model. PubMedBERT captures the
    fine-grained clinical authority distinctions that matter for output
    guardrails (e.g. "the patient likely has X" vs "the patient has X").

    The Incremental Escalation (#6) defense:
    ─────────────────────────────────────────
    Before encoding, we prepend the last ESCALATION_CONTEXT_TURNS turns of
    conversation to the response. A statement like "I will allocate ICU-04"
    is borderline alone; when prepended with 3 turns of vitals discussion
    that pushed the LLM toward a triage role, the combined embedding shifts
    into the clinical-decision zone and triggers the block.
    """

    def __init__(
        self,
        qdrant_host: str = "localhost",
        qdrant_port: int = 6333,
        use_in_memory: bool = True,
    ):
        logger.info("OutputSemanticScanner: loading model %s", EMBEDDING_MODEL_ID)
        self._model  = SentenceTransformer(EMBEDDING_MODEL_ID)

        if use_in_memory:
            self._client = QdrantClient(":memory:")
        else:
            self._client = QdrantClient(host=qdrant_host, port=qdrant_port)

        self._ensure_collection()

    def _ensure_collection(self) -> None:
        existing = [c.name for c in self._client.get_collections().collections]
        if OUTPUT_COLLECTION_NAME not in existing:
            self._client.create_collection(
                collection_name=OUTPUT_COLLECTION_NAME,
                vectors_config=qdrant_models.VectorParams(
                    size=VECTOR_DIM,
                    distance=qdrant_models.Distance.COSINE,
                ),
            )

    def seed_from_json(self, seeds_json_path: str = "data/output_vector_seeds.json") -> int:
        """
        Load seeds from data/output_vector_seeds.json.
        """
        p = Path(seeds_json_path)
        if not p.exists():
            logger.warning("Output seeds not found: %s", seeds_json_path)
            return 0
        with p.open() as f:
            seeds: list[dict] = json.load(f)

        points = []
        for seed in seeds:
            vector = self._model.encode(seed["query"], normalize_embeddings=True).tolist()
            pid = int(hashlib.md5(seed["query"].encode()).hexdigest()[:8], 16)
            points.append(qdrant_models.PointStruct(
                id=pid,
                vector=vector,
                payload={
                    "label":  seed["label"],
                    "weight": seed.get("weight", 5.0),
                    "agent":  seed.get("agent", "ALL"),
                },
            ))
        self._client.upsert(collection_name=OUTPUT_COLLECTION_NAME, points=points)
        logger.info("OutputSemanticScanner: upserted %d seeds", len(points))
        return len(points)

    def scan(
        self,
        response_text: str,
        agent: str,
        conversation_history: Optional[list[dict]] = None,
    ) -> Optional[Layer4Result]:
        """
        Scan the response (+ trailing context) for prohibited output.
        conversation_history: list of {"role": ..., "content": ...} dicts.
        """
        # Build scanning window: recent context + current response
        context_snippet = ""
        if conversation_history:
            recent = conversation_history[-ESCALATION_CONTEXT_TURNS:]
            context_snippet = " ".join(
                turn.get("content", "")
                for turn in recent
                if turn.get("role") == "assistant"
            )

        response_text = _strip_think_blocks(response_text)
        scan_text = (context_snippet + " " + response_text).strip()
        if not scan_text:
            return None

        query_vector = self._model.encode(scan_text, normalize_embeddings=True).tolist()

        search_filter = qdrant_models.Filter(
            should=[
                qdrant_models.FieldCondition(
                    key="agent", match=qdrant_models.MatchValue(value=agent)
                ),
                qdrant_models.FieldCondition(
                    key="agent", match=qdrant_models.MatchValue(value="ALL")
                ),
            ]
        )

        results = self._client.search(
            collection_name=OUTPUT_COLLECTION_NAME,
            query_vector=query_vector,
            limit=K_NEAREST,
            query_filter=search_filter,
            with_payload=True,
        )

        if not results:
            return None

        max_sim    = results[0].score
        top_result = results[0]

        if max_sim >= OUTPUT_BLOCK_THRESHOLD:
            return Layer4Result(
                decision=Layer4Decision.BLOCK,
                stage="semantic",
                violation_type=top_result.payload.get("label"),
                matched_label=top_result.payload.get("label"),
                confidence=max_sim,
            )

        if max_sim >= OUTPUT_GREY_ZONE_LOWER:
            vote = sum(r.score * r.payload.get("weight", 1.0) for r in results)
            if vote >= OUTPUT_GREY_VOTE_THRESHOLD:
                return Layer4Result(
                    decision=Layer4Decision.BLOCK,
                    stage="semantic_grey_zone",
                    violation_type=top_result.payload.get("label"),
                    matched_label=top_result.payload.get("label"),
                    confidence=max_sim,
                )

        return None


# ─────────────────────────────────────────────────────────────────────────────
# Public entry point
# ─────────────────────────────────────────────────────────────────────────────

class Layer4Guard:
    """
    Intercepts the Worker LLM response before it reaches the UI.
    Instantiate once at app startup; call .scan() on every agent response.
    """

    def __init__(
        self,
        output_exact_patterns_path: str  = "data/output_exact_patterns.json",  # ignored
        output_seeds_path:          str  = "data/output_vector_seeds.json",
        qdrant_host:                str  = "localhost",
        qdrant_port:                int  = 6333,
        use_in_memory_qdrant:       bool = True,
    ):
        # exact pattern path is ignored — purely semantic
        _ = output_exact_patterns_path

        self._semantic = OutputSemanticScanner(qdrant_host, qdrant_port, use_in_memory_qdrant)
        self._semantic.seed_from_json(output_seeds_path)

    def scan(
        self,
        response_text: str,
        agent: str,
        conversation_history: Optional[list[dict]] = None,
    ) -> Layer4Result:
        """
        Full Layer 4 scan (strictly semantic).

        Args:
            response_text:        The Worker LLM's complete response string.
            agent:                "ADITI" | "NINA" | "DIANA" | "PAMA"
            conversation_history: Full prior turns for escalation detection.

        Returns:
            Layer4Result. If decision != PASS, use .safe_response instead of
            the original response_text.
        """
        t0 = time.perf_counter()
        fallback = AGENT_FALLBACKS.get(agent, "Please consult the appropriate staff.")
        safe = SCRUBBED_RESPONSE_TEMPLATE.format(agent_fallback=fallback)

        # ── No XML/structural scan. Strictly semantic. ────────────────────────
        result = self._semantic.scan(response_text, agent, conversation_history)

        if result is not None:
            result.latency_ms  = (time.perf_counter() - t0) * 1000
            result.safe_response = safe
            logger.warning(
                "Layer4 BLOCK [%s] agent=%s violation=%s conf=%.3f response=%.60r",
                result.stage, agent, result.violation_type,
                result.confidence, response_text,
            )
            return result

        latency = (time.perf_counter() - t0) * 1000
        logger.debug(
            "Layer4 PASS agent=%s latency=%.1f ms response=%.60r",
            agent, latency, response_text,
        )
        return Layer4Result(
            decision=Layer4Decision.PASS,
            stage="none",
            latency_ms=latency,
            safe_response=response_text,
        )