"""
EKAYAA — Layer 1 Input Guardrails  (semantic-only, v3)
Semantic k-NN VectorDB shield (pre-LLM).

Architecture decision:
  Embedding model : BAAI/bge-large-en-v1.5
                    (state-of-the-art general-purpose English encoder, 1024-dim,
                     outperforms PubMedBERT on MTEB retrieval benchmarks;
                     suitable for adversarial/jailbreak pattern detection at input)
  VectorDB        : Qdrant (in-memory for dev, server-mode for prod)
                    Chosen over FAISS: native payload filtering lets us store {label, weight,
                    agent, taxonomy_id} alongside vectors without extra lookup tables.
                    Chosen over Chroma: better concurrency, gRPC batching, and native
                    binary quantisation for the clinical embedding space.

Decision (single stage):
  Semantic k-NN arbiter : cosine similarity against seeded VectorDB, ~5-15 ms

  max_sim >= SEMANTIC_BLOCK_THRESHOLD         → hard BLOCK
  GREY_ZONE_LOWER <= max_sim < threshold      → weighted vote
  max_sim < GREY_ZONE_LOWER                   → PASS

The exact-match firewall (Stage 1) that previously ran before the semantic
check has been removed. Reasons:

  1. 3,105 substring patterns at O(n) produce false positives at scale
     (legitimate clinical sentences contain the exact phrases being blocked).
  2. Patterns miss paraphrases, synonyms, adversarial character substitution,
     and multilingual inputs — the semantic layer handles all of these.
  3. The pattern list requires manual maintenance per attack vector. The seed
     corpus (input_vector_seeds.json) generalises to novel phrasing without
     manual updates.
  4. The grey-zone weighted vote already provides the graduated sensitivity
     that the exact-match layer was added to supplement.

The structural/XML tag scan from Layer 4 (output) has no input-side analogue
and is not added here. Input messages are user text; structural leakage is
an output-side concern.

Seed file: data/input_vector_seeds.json
  (generated by: python seed_patterns.py --role input --model BAAI/bge-large-en-v1.5
                                         --output data/input_vector_seeds.json)
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
import time
import unicodedata
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Optional

from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient
from qdrant_client.http import models as qdrant_models

logger = logging.getLogger("ekayaa.layer1")

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

EMBEDDING_MODEL_ID = "BAAI/bge-large-en-v1.5"
COLLECTION_NAME    = "ekayaa_adversarial_patterns"
VECTOR_DIM         = 1024         # BGE-large hidden size (NOT 768 — do not change)

# BGE models require a query prefix for retrieval tasks.
BGE_QUERY_PREFIX   = "Represent this sentence for searching relevant passages: "

# Decision thresholds — tuned so that a weight-5.0 seed at distance ≤0.25
# is a definitive block and weight-4.8 at ≤0.30 is still blocked.
SEMANTIC_BLOCK_THRESHOLD  = 0.70   # cosine similarity (0–1); tightened from 0.72
                                   # after removing exact-match safety net
GREY_ZONE_LOWER           = 0.52   # tightened from 0.55 for same reason
GREY_ZONE_UPPER           = SEMANTIC_BLOCK_THRESHOLD
K_NEAREST                 = 5      # neighbours to retrieve

# Safe fallback message sent back to the caller when a block fires
BLOCK_RESPONSE = (
    "I'm sorry, I'm not able to help with that request. "
    "Please contact the appropriate clinical or administrative staff directly."
)

# ─────────────────────────────────────────────────────────────────────────────
# Data classes
# ─────────────────────────────────────────────────────────────────────────────

class Layer1Decision(str, Enum):
    PASS  = "PASS"
    BLOCK = "BLOCK"

@dataclass
class Layer1Result:
    decision:        Layer1Decision
    stage:           str                    # "semantic_knn" | "semantic_knn_grey_zone" | "none"
    matched_label:   Optional[str] = None
    matched_rule:    Optional[str] = None
    confidence:      float         = 0.0
    latency_ms:      float         = 0.0
    block_response:  str           = BLOCK_RESPONSE


# ─────────────────────────────────────────────────────────────────────────────
# Pre-processing pipeline
# ─────────────────────────────────────────────────────────────────────────────

def _strip_invisible(text: str) -> str:
    return "".join(ch for ch in text if unicodedata.category(ch) != "Cf")

def _strip_xml_tags(text: str) -> str:
    return re.sub(r"<[^>]+>", " ", text)

def _strip_code_fences(text: str) -> str:
    return re.sub(r"```[^`]*```", " ", text, flags=re.DOTALL)

def preprocess(raw: str) -> str:
    """
    Normalise input before embedding.
    Order: invisible-char strip → unicode NFC → XML strip →
    code-fence strip → whitespace collapse → lowercase.
    """
    text = _strip_invisible(raw)
    text = unicodedata.normalize("NFC", text)
    text = _strip_xml_tags(text)
    text = _strip_code_fences(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text.lower()


# ─────────────────────────────────────────────────────────────────────────────
# Semantic k-NN arbiter (Qdrant + BGE-large-en-v1.5)
# ─────────────────────────────────────────────────────────────────────────────

class SemanticGuard:
    """
    Embeds the user query and retrieves the k-nearest seeds from Qdrant.
    Decision logic:

        max_sim >= SEMANTIC_BLOCK_THRESHOLD             → hard BLOCK
        GREY_ZONE_LOWER <= max_sim < SEMANTIC_BLOCK_THRESHOLD →
            weighted vote: sum(weight * sim) for top-k;
            if vote_score >= grey_zone_vote_threshold   → BLOCK
        max_sim < GREY_ZONE_LOWER                       → PASS

    The weight field on each seed (4.8–6.5 in the Patterns.docx) acts as a
    per-seed sensitivity amplifier in the grey zone.

    BGE note: BGE-large-en-v1.5 encodes documents and queries differently.
    At query time we prepend BGE_QUERY_PREFIX to the text; seeds are encoded
    WITHOUT the prefix (they are documents, not queries).
    """

    GREY_ZONE_VOTE_THRESHOLD = 3.2  # tightened from 3.5 after removing exact-match

    def __init__(
        self,
        qdrant_host: str = "localhost",
        qdrant_port: int = 6333,
        use_in_memory: bool = True,
    ):
        logger.info("Loading embedding model: %s", EMBEDDING_MODEL_ID)
        self._model = SentenceTransformer(EMBEDDING_MODEL_ID)

        if use_in_memory:
            self._client = QdrantClient(":memory:")
            logger.info("SemanticGuard: using in-memory Qdrant (dev mode)")
        else:
            self._client = QdrantClient(host=qdrant_host, port=qdrant_port)
            logger.info("SemanticGuard: connecting to Qdrant at %s:%s", qdrant_host, qdrant_port)

        self._ensure_collection()

    def _ensure_collection(self) -> None:
        existing = [c.name for c in self._client.get_collections().collections]
        if COLLECTION_NAME not in existing:
            self._client.create_collection(
                collection_name=COLLECTION_NAME,
                vectors_config=qdrant_models.VectorParams(
                    size=VECTOR_DIM,
                    distance=qdrant_models.Distance.COSINE,
                ),
            )
            logger.info("SemanticGuard: created Qdrant collection '%s'", COLLECTION_NAME)

    def seed_from_patterns_json(self, seeds_json_path: str = "data/input_vector_seeds.json") -> int:
        """
        Upserts all VectorDB seeds from data/input_vector_seeds.json into Qdrant.
        Called once at startup (or whenever patterns are updated).

        Seeds are encoded WITHOUT the query prefix — they are stored as
        documents. Only queries at inference time use BGE_QUERY_PREFIX.
        """
        path = Path(seeds_json_path)
        if not path.exists():
            logger.warning("Seeds file not found: %s", seeds_json_path)
            return 0

        with path.open() as f:
            seeds: list[dict] = json.load(f)

        points = []
        for seed in seeds:
            vector = self._model.encode(seed["query"], normalize_embeddings=True).tolist()
            point_id = int(hashlib.md5(seed["query"].encode()).hexdigest()[:8], 16)
            points.append(
                qdrant_models.PointStruct(
                    id=point_id,
                    vector=vector,
                    payload={
                        "label":       seed["label"],
                        "weight":      seed["weight"],
                        "agent":       seed.get("agent", "ALL"),
                        "taxonomy_id": seed.get("taxonomy_id", ""),
                    },
                )
            )

        self._client.upsert(collection_name=COLLECTION_NAME, points=points)
        logger.info("SemanticGuard: upserted %d seeds into Qdrant", len(points))
        return len(points)

    def check(self, preprocessed_text: str, agent_filter: Optional[str] = None) -> Optional[Layer1Result]:
        """
        Embed text (with BGE query prefix), search Qdrant, apply threshold logic.
        agent_filter: if set, restricts search to seeds for that agent.
        """
        query_text   = BGE_QUERY_PREFIX + preprocessed_text
        query_vector = self._model.encode(query_text, normalize_embeddings=True).tolist()

        search_filter = None
        if agent_filter:
            search_filter = qdrant_models.Filter(
                should=[
                    qdrant_models.FieldCondition(
                        key="agent",
                        match=qdrant_models.MatchValue(value=agent_filter),
                    ),
                    qdrant_models.FieldCondition(
                        key="agent",
                        match=qdrant_models.MatchValue(value="ALL"),
                    ),
                ]
            )

        results = self._client.search(
            collection_name=COLLECTION_NAME,
            query_vector=query_vector,
            limit=K_NEAREST,
            query_filter=search_filter,
            with_payload=True,
        )

        if not results:
            return None  # collection empty → pass through (fail-open for dev)

        max_sim    = results[0].score
        top_result = results[0]

        # Safe-label bypass — if the nearest neighbour is a safe seed,
        # the message is in the safe zone regardless of similarity score.
        # Safe seeds anchor the vector space around legitimate requests so
        # adversarial seeds don't capture them by proximity.
        SAFE_LABELS = {
            "safe_administrative_request",
            "safe_logistical_request",
            "safe_patient_query",
            "safe_workflow_request",
            "safe_registration_request",
            "safe_handover_request",
            "safe_nursing_task",
            "safe_billing_query",
        }
        if top_result.payload.get("label") in SAFE_LABELS:
            return None  # PASS — nearest neighbour is a safe seed

        # Hard block
        if max_sim >= SEMANTIC_BLOCK_THRESHOLD:
            return Layer1Result(
                decision=Layer1Decision.BLOCK,
                stage="semantic_knn",
                matched_label=top_result.payload.get("label"),
                matched_rule=(
                    f"agent={top_result.payload.get('agent')} "
                    f"tax={top_result.payload.get('taxonomy_id')}"
                ),
                confidence=max_sim,
            )

        # Grey zone — weighted vote
        if max_sim >= GREY_ZONE_LOWER:
            vote_score = sum(r.score * r.payload.get("weight", 1.0) for r in results)
            if vote_score >= self.GREY_ZONE_VOTE_THRESHOLD:
                return Layer1Result(
                    decision=Layer1Decision.BLOCK,
                    stage="semantic_knn_grey_zone",
                    matched_label=top_result.payload.get("label"),
                    matched_rule=f"grey_zone_vote={vote_score:.2f}",
                    confidence=max_sim,
                )

        return None  # PASS


# ─────────────────────────────────────────────────────────────────────────────
# Public entry point
# ─────────────────────────────────────────────────────────────────────────────

class Layer1Guard:
    """
    Single-stage semantic guardrail.
    Instantiate once at app startup; call .check() on every incoming message.

    The patterns_json_path parameter is accepted for backwards compatibility
    with callers that pass it, but is silently ignored — exact-match
    pattern loading has been removed.
    """

    def __init__(
        self,
        patterns_json_path:   str  = "data/exact_patterns.json",  # ignored (backwards compat)
        seeds_json_path:      str  = "data/input_vector_seeds.json",
        qdrant_host:          str  = "localhost",
        qdrant_port:          int  = 6333,
        use_in_memory_qdrant: bool = True,
    ):
        _ = patterns_json_path  # explicitly discard — no longer used
        self._semantic = SemanticGuard(qdrant_host, qdrant_port, use_in_memory_qdrant)
        self._semantic.seed_from_patterns_json(seeds_json_path)

    def check(
        self,
        raw_message: str,
        agent_hint: Optional[str] = None,
    ) -> Layer1Result:
        """
        Full Layer 1 check pipeline.

        Args:
            raw_message: The user's raw input string (or the harness trigger).
            agent_hint:  Downstream agent context (ADITI / NINA / DIANA / PAMA)
                         if already known, enables targeted seed filtering.
                         The harness passes persona.toUpperCase() from the
                         POST body.

        Returns:
            Layer1Result with decision = PASS or BLOCK.
        """
        t0    = time.perf_counter()

        # ── Auto-continuation whitelist ───────────────────────────────────────
        # The harness fires synthetic triggers of the form:
        #   "Now in <STATE>. Continue as per the workflow."
        # These are internal FSM signals, not user input. They must never be
        # blocked by the input guard — doing so silently kills every
        # auto-advancing workflow turn.
        import re as _re
        if _re.match(r"^Now in [A-Z_]+\. Continue as per the workflow\.$", raw_message.strip()):
            latency = (time.perf_counter() - t0) * 1000
            logger.debug("Layer1 PASS [auto_continuation_whitelist] latency=%.1f ms", latency)
            return Layer1Result(
                decision=Layer1Decision.PASS,
                stage="auto_continuation_whitelist",
                latency_ms=latency,
            )

        clean = preprocess(raw_message)

        result = self._semantic.check(clean, agent_filter=agent_hint)
        if result is not None:
            result.latency_ms = (time.perf_counter() - t0) * 1000
            logger.warning(
                "Layer1 BLOCK [%s] label=%s conf=%.3f text=%.80r",
                result.stage, result.matched_label, result.confidence, raw_message,
            )
            return result

        latency = (time.perf_counter() - t0) * 1000
        logger.debug("Layer1 PASS latency=%.1f ms text=%.80r", latency, raw_message)
        return Layer1Result(
            decision=Layer1Decision.PASS,
            stage="none",
            latency_ms=latency,
        )